//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Databases
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tools
    {
        public int ID { get; set; }
        public string Manufacturer { get; set; }
        public string Model { get; set; }
        public string Mac { get; set; }
        public string IpAdress { get; set; }
        public string SerialNumber { get; set; }

        public Tools(int _id, String _manufacturer, String _model, String _mac, String _ipAdress, String _serialNumber)
        {
            this.ID = _id;
            this.Manufacturer = _manufacturer;
            this.Model = _model;
            this.Mac = _mac;
            this.IpAdress = _ipAdress;
            this.SerialNumber = _serialNumber;
        }
        public Tools() { }
    }
}
